name: Deploy to EC2

on:
  push:
    branches:
      - deploy-#37

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 원격접속으로 ec2 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            java -jar *SNAPSHOT.jar > ./output.log 2>&1 &
